### PR TITLE
fix: 🐛 transpile build

### PR DESCRIPTION
**Pull request by mvasin**
With the previous setup, build wasn't transpiled with babel, because `babel-loader` was not used in the webpack config.

Here's the difference in the build before and after changes:
Screenshot 2020-02-08 at 11 58 03
You can tell that output was ES6, not ES5, that for instance creates problems for `uglify-js` (that I use in my project) which does not support ES6.

This fix can potentially help with issue #51 (notice there are `const` used throughout the build, while IE11 supports `const` [only partially](https://caniuse.com/#search=const), and there are probably other ES6-related quirks in IE11), but I did not test that.

### CODE REVIEW

**Comment by baruchvlz** [comment]
Thanks for fixing this. Could you fix the merge conflicts?

**Comment by mvasin** [comment]
@baruchvlz Done! But please have a look at this article: https://dev.to/gajus/stop-using-package-lock-json-or-yarn-lock-3ddi It is recommended to add lock files to applications, not to libraries.

**Comment by baruchvlz** [comment]
@mvasin Thanks for sharing that article, does make sense not to have a lock file for libraries. If you'd like you can remove the yarn.lock file and add it to the gitignore in this PR.

**Comment by mvasin** [comment]
Done!

**Comment by baruchvlz** [comment]
Thanks for taking care of this.

**Pull request merged**
